services:
  core:
    build:
      context: ./core
    container_name: intentverse-core
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mcp:
    build:
      context: ./mcp
    container_name: intentverse-mcp
    ports:
      - "8001:8001"
    volumes:
      - ./mcp:/app
    environment:
      - PYTHONPATH=/app
    command: python app/main.py
    depends_on:
      core:
        condition: service_healthy

  web:
    build:
      context: ./web
    working_dir: /app
    container_name: intentverse-web
    ports:
      - "3000:3000"
    volumes:
      - ./web/src:/app/src
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - core

  tests:
    build:
      context: ./core
    container_name: intentverse-tests
    volumes:
      - ./core:/app
    environment:
      - PYTHONPATH=/app
    command: ["python", "-m", "pytest"]
    depends_on:
      core:
        condition: service_healthy
    profiles:
      - tests

networks:
  default:
    name: intentverse-net