services:
  # The Core Engine service (FastAPI backend)
  core:
    build:
      context: ./core
    container_name: intentverse-core
    ports:
      - "8000:8000"
    volumes:
      - ./core/app:/app/app
      - ./core/tests:/app/tests
    # Set the PYTHONPATH to the root of our code inside the container
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - intentverse-net

  # The MCP Interface service (fastmcp server)
  mcp:
    build:
      context: ./mcp
    container_name: intentverse-mcp
    ports:
      - "8001:8001"
    volumes:
      - ./mcp/app:/app/app
    environment:
      - PYTHONPATH=/app
    command: python app/main.py
    depends_on:
      - core
    networks:
      - intentverse-net

  # The Web UI service (React/Vue/Svelte frontend)
  web:
    build:
      context: ./web
    container_name: intentverse-web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    environment:
      - WATCHPACK_POLLING=true
    command: npm start
    depends_on:
      - core
    networks:
      - intentverse-net

networks:
  intentverse-net:
    driver: bridge