services:
  core:
    build:
      context: ./core
    container_name: intentverse-core
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    environment:
      - PYTHONPATH=/app
      - SERVICE_API_KEY=dev-service-key-12345
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  mcp:
    build:
      context: ./mcp
    container_name: intentverse-mcp
    ports:
      - "8001:8001"
    volumes:
      - ./mcp:/app
    environment:
      - PYTHONPATH=/app
      - SERVICE_API_KEY=dev-service-key-12345
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    command: python -m app.main
    depends_on:
      core:
        condition: service_healthy

  web:
    build:
      context: ./web
    working_dir: /app
    container_name: intentverse-web
    ports:
      - "3000:3000"
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - core
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  tests:
    build:
      context: ./core
    container_name: intentverse-tests
    volumes:
      - ./core:/app
    environment:
      - PYTHONPATH=/app
      - SERVICE_API_KEY=dev-service-key-12345
      - CORE_API_URL=http://core:8000
    command: ["python", "-m", "pytest", "tests/", "-v", "--tb=short", "--disable-warnings"]
    depends_on:
      core:
        condition: service_healthy
    profiles:
      - tests

  mcp-tests:
    build:
      context: ./mcp
    container_name: intentverse-mcp-tests
    working_dir: /app
    volumes:
      - ./mcp:/app
    environment:
      - PYTHONPATH=/app
      - CORE_API_URL=http://core:8000
      - SERVICE_API_KEY=dev-service-key-12345
    command: ["python", "-m", "pytest", "tests/", "-v", "--tb=short", "--disable-warnings"]
    depends_on:
      core:
        condition: service_healthy
    profiles:
      - tests

  web-tests:
    build:
      context: ./web
    container_name: intentverse-web-tests
    working_dir: /app
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    environment:
      - CI=true
    command: ["npm", "test", "--", "--coverage", "--watchAll=false", "--ci"]
    depends_on:
      - core
    profiles:
      - tests

networks:
  default:
    name: intentverse-net