version: '3.8'

services:
  # MariaDB database for local development and testing
  mariadb:
    image: mariadb:10.11
    container_name: intentverse-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: intentverse
      MARIADB_USER: intentverse_user
      MARIADB_PASSWORD: intentverse_pass
      MARIADB_CHARSET: utf8mb4
      MARIADB_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-scripts-mysql:/docker-entrypoint-initdb.d
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO
      --max-connections=100
      --innodb-buffer-pool-size=256M
      --innodb-log-file-size=64M
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/slow.log
      --long-query-time=1
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - intentverse-network

  # IntentVerse Core with MariaDB
  intentverse-core:
    build:
      context: ../../core
      dockerfile: Dockerfile
    container_name: intentverse-core-mariadb
    environment:
      # MariaDB configuration (uses MySQL implementation)
      INTENTVERSE_DB_TYPE: mariadb
      INTENTVERSE_DB_HOST: mariadb
      INTENTVERSE_DB_PORT: 3306
      INTENTVERSE_DB_NAME: intentverse
      INTENTVERSE_DB_USER: intentverse_user
      INTENTVERSE_DB_PASSWORD: intentverse_pass
      INTENTVERSE_DB_SSL_MODE: PREFERRED
      INTENTVERSE_DB_CHARSET: utf8mb4
      INTENTVERSE_DB_POOL_SIZE: 10
      INTENTVERSE_DB_MAX_OVERFLOW: 20
      INTENTVERSE_DB_SQL_MODE: STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO
      
      # Other configuration
      INTENTVERSE_LOG_LEVEL: INFO
    ports:
      - "8000:8000"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - intentverse-network
    volumes:
      - ../../core/content_packs:/app/content_packs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web interface
  intentverse-web:
    build:
      context: ../../web
      dockerfile: Dockerfile
    container_name: intentverse-web-mariadb
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - intentverse-core
    networks:
      - intentverse-network

volumes:
  mariadb_data:
    driver: local

networks:
  intentverse-network:
    driver: bridge