version: '3.8'

services:
  # PostgreSQL database for local development and testing
  postgres:
    image: postgres:15-alpine
    container_name: intentverse-postgres
    environment:
      POSTGRES_DB: intentverse
      POSTGRES_USER: intentverse_user
      POSTGRES_PASSWORD: intentverse_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U intentverse_user -d intentverse"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - intentverse-network

  # IntentVerse Core with PostgreSQL
  intentverse-core:
    build:
      context: ../../core
      dockerfile: Dockerfile
    container_name: intentverse-core-postgres
    environment:
      # PostgreSQL configuration
      INTENTVERSE_DB_TYPE: postgresql
      INTENTVERSE_DB_HOST: postgres
      INTENTVERSE_DB_PORT: 5432
      INTENTVERSE_DB_NAME: intentverse
      INTENTVERSE_DB_USER: intentverse_user
      INTENTVERSE_DB_PASSWORD: intentverse_pass
      INTENTVERSE_DB_SSL_MODE: prefer
      INTENTVERSE_DB_POOL_SIZE: 10
      INTENTVERSE_DB_MAX_OVERFLOW: 20
      INTENTVERSE_DB_APPLICATION_NAME: IntentVerse-Core
      
      # Other configuration
      INTENTVERSE_LOG_LEVEL: INFO
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - intentverse-network
    volumes:
      - ../../core/content_packs:/app/content_packs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web interface
  intentverse-web:
    build:
      context: ../../web
      dockerfile: Dockerfile
    container_name: intentverse-web-postgres
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - intentverse-core
    networks:
      - intentverse-network

volumes:
  postgres_data:
    driver: local

networks:
  intentverse-network:
    driver: bridge