services:
  core:
    image: intentverse/intentverse-core:v1.0.0
    container_name: intentverse-core
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - SERVICE_API_KEY=dev-service-key-12345
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  mcp:
    image: intentverse/intentverse-mcp:v1.0.0
    container_name: intentverse-mcp
    working_dir: /app
    ports:
      - "8001:8001"
    environment:
      - CORE_API_URL=http://core:8000
      - PYTHONPATH=/app
      - SERVICE_API_KEY=dev-service-key-12345
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    command: python -m app.main
    depends_on:
      core:
        condition: service_healthy

  web:
    image: intentverse/intentverse-web:v1.0.0
    working_dir: /app
    container_name: intentverse-web
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - core
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  default:
    name: intentverse-net