name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build all service images
        run: docker compose build

      - name: Run core tests
        run: docker compose up tests --build --abort-on-container-exit

      - name: Run MCP tests
        run: docker compose up mcp-tests --build --abort-on-container-exit

  # This is the new job we are adding
  gitleaks-scan:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need to fetch the entire history for Gitleaks to scan everything
          fetch-depth: 0

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          # The GITHUB_TOKEN is automatically provided by GitHub
          # The action will fail the job if secrets are found.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}